apiVersion: v1
kind: Service
metadata:
  name: romulus-backend-nodeport
  namespace: romulus
spec:
  selector:
    app: romulus-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
