apiVersion: v1
kind: Service
metadata:
  name: romulus-postgres
  namespace: romulus
spec:
  selector:
    app: romulus-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
