"""create worker and sandbox tables

Revision ID: 537e2198d0b7
Revises: 0bc3200513d3
Create Date: 2026-04-04 20:32:30.408945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '537e2198d0b7'
down_revision: Union[str, Sequence[str], None] = '0bc3200513d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'failed', 'terminating', 'terminated', name='workerstatus'), nullable=False),
    sa.Column('worker_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deployment_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nodeport_service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_workspace_id'), 'sandbox', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandbox_workspace_id'), table_name='sandbox')
    op.drop_table('sandbox')
    op.drop_table('worker')
    op.execute("DROP TYPE IF EXISTS workerstatus")
    # ### end Alembic commands ###
